// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_UuLtPhX3oV6BO0fxC6DXHunSmy08-Y',
    appId: '1:869255876155:web:edc563fb7570506d31561e',
    messagingSenderId: '869255876155',
    projectId: 'fir-cicd-13b56',
    authDomain: 'fir-cicd-13b56.firebaseapp.com',
    storageBucket: 'fir-cicd-13b56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz5iqNSjwWhRx2MZlt5h5hXyOztezc6kQ',
    appId: '1:869255876155:android:f4780ceb9f6a05e531561e',
    messagingSenderId: '869255876155',
    projectId: 'fir-cicd-13b56',
    storageBucket: 'fir-cicd-13b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy5Si--BKWaU1UJt9agZzRPlBkVpRPGV4',
    appId: '1:869255876155:ios:c4c4bea518ce672331561e',
    messagingSenderId: '869255876155',
    projectId: 'fir-cicd-13b56',
    storageBucket: 'fir-cicd-13b56.appspot.com',
    iosClientId: '869255876155-tf1vicc4vqntrfrq96mnbi5n8ho7cn80.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCicd',
  );
}
